In [1]:
import torch
t_one =torch.Tensor([[1,1,1],[2,2,2],[3,3,3]]) 
print(t_one)
import sklearn

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.]])


In [42]:
import torch.nn as nn
model=nn.Linear(1,1)
for i in model.named_parameters():
    print(i)

('weight', Parameter containing:
tensor([[-0.6081]], requires_grad=True))
('bias', Parameter containing:
tensor([0.6983], requires_grad=True))


In [6]:
import torch.nn as nn

model = nn.Linear(1,1)

for i in model.named_parameters():
    print(i)

('weight', Parameter containing:
tensor([[0.0696]], requires_grad=True))
('bias', Parameter containing:
tensor([0.8162], requires_grad=True))


In [ ]:
import inspect
import sklearn

models = [sklearn.linear_model.LinearRegression]
for m in models:
    hyperparams = inspect.signature(m.__init__)
    print(hyperparams)
 

In [ ]:
t_two =torch.Tensor([[1,1,1],[2,2,2],[3,3,3]]) 
print(t_two)

In [ ]:
dot_prod=torch.mm(t_one,t_two)
print(dot_prod)

In [ ]:
import torch
#forword pass
w=torch.tensor(1.0,requires_grad=True)
x=torch.tensor(1.0)
y=torch.tensor(2.0)
#forword pass ip op 
yy=w*x
loss=(y-yy)**2
#backward pass going back from op and apply grad for ip
loss.backward()
print(w.grad)


In [ ]:
# import torch.nn as nn

# #model = nn.Linear(1,1)
# for j in model.named_parameters():
#     if j.requires_grad:
#         #print(j)   
#         print(j)

In [ ]:
#stochastic .graddescent in pytorch optimizers


import torch
from torch.nn import MSELoss, Parameter

# The data function is: y = x + 10
x_train = torch.tensor([1, 2, 3, 4])
y_train = torch.tensor([11.0, 12.0, 13.0, 14.0])#, dtype=torch.float

# Simple Linear Regression: a + bx
a = torch.randn(1, requires_grad=True, dtype=torch.float)
b = torch.randn(1, requires_grad=True, dtype=torch.float)

# If we use nn.Module to create a model, it will model.parameters()
model = [Parameter(a), Parameter(b)]

criterion = MSELoss()
# optimizer = torch.optim.SGD(model, lr=0.1)
optimizer = torch.optim.Adam(model, lr=0.1)

for epoch in range(10):#500
    # Remove the grad computed in the last step
    optimizer.zero_grad()
    # Run a + bx
    y_predicted = model[0] + model[1] * x_train
    print(x_train, y_train, y_predicted)
    loss = criterion(y_predicted, y_train)
    loss.backward()
    print("los is ",loss)
    optimizer.step()
    #print(model[0].grad)
    #rint(model[1].grad)
 
    
    
    
    
    

In [ ]:
import torch.nn as nn

model = nn.Linear(1,1)
for i,j in model.named_parameters():
        if j.requires_grad:
            print(j )

In [10]:
import torch.nn as nn

#model = nn.Linear(1,1)
for i,j in model.named_parameters():
        print(j)   
    

Parameter containing:
tensor([0.8162], requires_grad=True)
Parameter containing:
tensor([0.8162], requires_grad=True)


In [11]:
for i in model.named_parameters():
    print(i)



('weight', Parameter containing:
tensor([[0.0696]], requires_grad=True))
('bias', Parameter containing:
tensor([0.8162], requires_grad=True))


In [47]:
# SGD: Stochastic Gradient Descent
# Useful links
# https://ruder.io/optimizing-gradient-descent/
# https://towardsdatascience.com/understanding-pytorch-with-an-example-a-step-by-step-tutorial-81fc5f8c4e8e

# STEPS
# 1. Compute Loss
# 2. Compute Partial Derivatives
# 3. Update the Parameters
# 4. Repeat 1-3 until convergence


import torch
from torch.nn import MSELoss, Parameter

# The data function is: y = x + 10
x_train = torch.tensor([1, 2, 3, 4])
y_train = torch.tensor([11, 12, 13, 14], dtype=torch.float)

# Simple Linear Regression: a + bx
a = torch.randn(1, requires_grad=True, dtype=torch.float)
b = torch.randn(1, requires_grad=True, dtype=torch.float)

# If we use nn.Module to create a model, it will model.parameters()
model = [Parameter(a), Parameter(b)]

criterion = MSELoss()
# optimizer = torch.optim.SGD(model, lr=0.1)
optimizer = torch.optim.Adam(model, lr=0.1)

for epoch in range(500):
    # Remove the grad computed in the last step
    optimizer.zero_grad()
    # Run a + bx
    #y_predicted = model[0] + model[1] * x_train
    y_predicted =model(x_train)
    if epoch % 10 == 0:
        print(x_train, y_train, y_predicted)
        loss = criterion(y_predicted, y_train)
        loss.backward()
        print(loss)
    optimizer.step()
#     print(model[0].grad)
#     print(model[1].grad)
  
   
    # To get the model hyperparameters before you instantiate the class.

  

TypeError: 'list' object is not callable

In [ ]:
import inspect
import sklearn
a = sklearn.ensemble.RandomForestRegressor
models = [sklearn.ensemble.RandomForestRegressor, sklearn.linear_model.LinearRegression]

for m in models:
    hyperparams = 
    #inspect.getargspec(m.__init__).args
    print(hyperparams) # Do something with them here


In [ ]:
import inspect
import sklearn

from sklearn.ensemble import RandomForestRegressor
reg = RandomForestClassifier()
params = reg.get_params()
# do something...
reg.set_params(params)
reg.fit(X,  y)

In [ ]:
import inspect
import sklearn
get_params(deep=True)

In [ ]:
# To get the model hyperparameters before you instantiate the class
import inspect
import sklearn

models = [sklearn.linear_model.LinearRegression]
for m in models:
    hyperparams = inspect.signature(m.__init__)
    print(hyperparams)

In [ ]:
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor

SVR._get_param_names()


In [38]:
# 12*1  1*12 =1*1 ///////////////////////////////////////////////
from sklearn.feature_extraction.text import CountVectorizer
document1 = 'Dog hates a cat It loves to go out and play'
document2 = 'Cat loves to play with a ball'

# converting sentences to lower case
document1 = document1.lower()
document2 = document2.lower()

# Intialize BoWs
count_vect = CountVectorizer()
# fit the corpus to CountVectorizer
count_vect.fit([document1, document2])

#--------print("feature names ", count_vect.get_feature_names())

# bag of word representation of document1
bow1 = count_vect.transform([document1])
t1=bow1.toarray()
print("Representation  ", t1)

# bag of word representation of document2
bow2 = count_vect.transform([document2])
t2=bow2.toarray()
print("Representation  ", t2)

# Output:
# feature names  ['and', 'ball', 'cat', 'dog', 'go', 'hates', 'it', 'loves', 'out', 'play', 'to', 'with']

# Representation of document1:  [[1 0 1 1 1 1 1 1 1 1 1 0]]
# Representation of document2:  [[0 1 1 0 0 0 0 1 0 1 1 1]]












import torch
import torch.nn as nn

# Linear regression
# f = w * x 

# here : f = 2 * x

# X = torch.tensor([[1], [2], [3], [4]], dtype=torch.float32)
# Y = torch.tensor([[2], [4], [6], [8]], dtype=torch.float32)
X = torch.tensor(t1, dtype=torch.float32)
Y = torch.tensor(t2, dtype=torch.float32)
print(Y.shape)
n_samples, n_features = X.shape
print(f'#samples: {n_samples}, #features: {n_features}')
# 0) create a test sample
X_test = torch.tensor(X, dtype=torch.float32)

# 1) Design Model, the model has to implement the forward pass!
# Here we can use a built-in model from PyTorch


# we can call this model with samples X
model = nn.Linear(12,1)


print(f'Prediction before training: = {model(X_test)}')    #practise

# 2) Define loss and optimizer
learning_rate = 0.01
n_iters = 100

loss = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# 3) Training loop
for epoch in range(n_iters):
    # predict = forward pass with our model
    y_predicted = model(X_test)

    # loss
    l = loss(Y, y_predicted)

    # calculate gradients = backward pass
    l.backward()

    # update weights
    optimizer.step()

    # zero the gradients after updating
    optimizer.zero_grad()
    
    if epoch % 10 == 0:
        print("hi")
        print('epoch ', epoch+1,' loss = ', l)
for i,j in model.named_parameters():
    print(i,j)
print()
print()
print(f"Prediction after training: {model(X_test)}")


Representation   [[1 0 1 1 1 1 1 1 1 1 1 0]]
Representation   [[0 1 1 0 0 0 0 1 0 1 1 1]]
torch.Size([1, 12])
#samples: 1, #features: 12
Prediction before training: = tensor([[-0.8725]], grad_fn=<AddmmBackward0>)
hi
epoch  1  loss =  tensor(2.1336, grad_fn=<MseLossBackward0>)
hi
epoch  11  loss =  tensor(0.2631, grad_fn=<MseLossBackward0>)
hi
epoch  21  loss =  tensor(0.2501, grad_fn=<MseLossBackward0>)
hi
epoch  31  loss =  tensor(0.2500, grad_fn=<MseLossBackward0>)
hi
epoch  41  loss =  tensor(0.2500, grad_fn=<MseLossBackward0>)
hi
epoch  51  loss =  tensor(0.2500, grad_fn=<MseLossBackward0>)
hi
epoch  61  loss =  tensor(0.2500, grad_fn=<MseLossBackward0>)
hi
epoch  71  loss =  tensor(0.2500, grad_fn=<MseLossBackward0>)
hi
epoch  81  loss =  tensor(0.2500, grad_fn=<MseLossBackward0>)
hi
epoch  91  loss =  tensor(0.2500, grad_fn=<MseLossBackward0>)
weight Parameter containing:
tensor([[ 0.2297, -0.1712, -0.1498,  0.0541,  0.1275,  0.2568,  0.0488, -0.0393,
         -0.1008,  0.0545,  

/tmp/ipykernel_374211/3846949331.py:60: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_test = torch.tensor(X, dtype=torch.float32)


learning rate=learning rate//2
loss=nn.MSELoss()
optimizer=torch.optim.SGD(model.parameters(),learning rate)
for epoch in range(100):
    y_predicted=model(X_test)
    l=loss(y,y_predicted)
    l.backword()
    optimizer.step()
    optimizer.zero_grad()
    