# numpy intro
**hi****


In [1]:
import numpy as np


In [78]:
arr=np.array([[1,2,3],[2,2,4],[2,3,0]] ,np.int32)

In [20]:
arr

array([[    1, 24445,     3],
       [    2,     2,     4],
       [    2,     3,     4]], dtype=int32)

In [4]:
arr[0]

array([    1, 24445,     3], dtype=int32)

In [5]:
arr[0,1]

24445

In [6]:
arr[1,2]

4

In [7]:
arr.shape

(2, 3)

In [8]:

arr[1,2]=45

In [9]:
arr

array([[    1, 24445,     3],
       [    2,     2,    45]], dtype=int32)

**arr creqtion**

In [16]:
arr.shape

(3, 3)

In [17]:
arr.size

9

In [23]:
arr=np.array({2,2,22,2})

In [24]:
arr

array({2, 22}, dtype=object)

In [28]:
zeros=np.zeros((4,4))

In [29]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
zeros.size

16

In [31]:
zeros.shape

(4, 4)

In [33]:
np.arange(13)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [38]:
k=np.linspace(5,50,10)

In [40]:
k

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [35]:
np.empty(50)

array([9.19851469e-317, 0.00000000e+000, 0.00000000e+000, 3.76773671e-317,
       2.27270197e-322, 6.92605196e-310, 6.92605196e-310, 6.92605194e-310,
       6.92605196e-310, 6.92605196e-310, 6.92605196e-310, 6.92605196e-310,
       6.92605196e-310, 6.92605193e-310, 6.92605195e-310, 6.92605196e-310,
       6.92605196e-310, 6.92605196e-310, 6.92605196e-310, 6.92605196e-310,
       6.92605196e-310, 6.92605196e-310, 6.92605196e-310, 6.92605196e-310,
       6.92605195e-310, 6.92605196e-310, 6.92605195e-310, 6.92605196e-310,
       6.92605196e-310, 6.92605196e-310, 6.92605197e-310, 6.92605196e-310,
       6.92605196e-310, 6.92605196e-310, 6.92605196e-310, 6.92605196e-310,
       6.92605196e-310, 6.92605196e-310, 6.92605196e-310, 6.92605196e-310,
       6.92605196e-310, 6.92605196e-310, 6.92605196e-310, 6.92605196e-310,
       6.92605196e-310, 6.92605196e-310, 6.92605196e-310, 6.92605196e-310,
       6.92605195e-310, 6.92605196e-310])

In [43]:
e_lik=np.empty_like(k)

In [44]:
e_lik

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [45]:
e_lik[0]=100

In [46]:
e_lik

array([100.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.])

In [58]:
l=np.identity(10)

In [55]:
l.shape

(10, 10)

In [56]:
l.size

100

In [68]:
k=l.reshape(5,20)

In [66]:
arr

array({2, 22}, dtype=object)

In [62]:
l

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [64]:
l

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [67]:
l

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [69]:
k

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1.]])

In [70]:
k.shape


(5, 20)

In [77]:
m=k.ravel()
m

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.])

In [74]:
m.size

100

In [75]:
m.shape

(100,)

In [79]:
arr


array([[1, 2, 3],
       [2, 2, 4],
       [2, 3, 0]], dtype=int32)

In [80]:
arr.sum(axis=0)

array([5, 7, 7])

In [83]:
arr.sum(axis=1)

array([6, 8, 5])

In [85]:
arr.T

AttributeError: 'numpy.ndarray' object has no attribute 't'

In [86]:
arr.ndim

2

In [87]:
arr.nbytes


36

In [96]:
k=arr.flat

In [100]:
for i in k:
    i

In [102]:
arr

array([[1, 2, 3],
       [2, 2, 4],
       [2, 3, 0]], dtype=int32)

In [101]:
arr.argmax()

5

In [104]:
arr.argmin(axis=0)

array([0, 0, 2])

In [106]:
arr.argmax(axis=1)

array([2, 2, 1])

#addditions

In [108]:
arr1=np.empty_like(arr)

In [109]:
arr1

array([[1, 2, 2],
       [2, 2, 3],
       [3, 4, 0]], dtype=int32)

In [110]:
arr

array([[1, 2, 3],
       [2, 2, 4],
       [2, 3, 0]], dtype=int32)

In [111]:
arr+arr1

array([[2, 4, 5],
       [4, 4, 7],
       [5, 7, 0]], dtype=int32)

In [114]:
arr1=np.array([[0,0,0],[0,0,0],[0,0,0]])

In [118]:
k=arr+arr1

In [116]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [1.41421356, 1.41421356, 2.        ],
       [1.41421356, 1.73205081, 0.        ]])

In [119]:
np.where(k>1)

(array([0, 0, 1, 1, 1, 2, 2]), array([1, 2, 0, 1, 2, 0, 1]))