In [1]:
import numpy as np 
import pandas as pd 
data_hound = pd.read_csv("hound.txt", delimiter='\t', header=None)
data_hound.columns = ["Review_text", "Review_class"]

data_sample = pd.read_csv("sample.txt", delimiter='\t', header=None)
data_sample.columns = ["Review_text", "Review_class"]

# data_yelp = pd.read_csv("yelp_labelled.txt", delimiter='\t', header=None)
# data_yelp.columns = ["Review_text", "Review_class"]

data = pd.concat([data_hound,data_sample])
data_hound.loc[1,["Review_text"]]

Review_text    Good case, Excellent value.
Name: 1, dtype: object

In [2]:
import re
import nltk

import string
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer


In [3]:
nltk.download('stopwords')
def clean_text(df):
    all_reviews = list()
    lines = df["Review_text"].values.tolist()
    for text in lines:
        text = text.lower()
        pattern = re.compile('http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+')
        text = pattern.sub('', text)
        text = re.sub(r"[,.\"!@#$%^&*(){}?/;`~:<>+=-]", "", text)
        tokens = word_tokenize(text)
        table = str.maketrans('', '', string.punctuation)
        stripped = [w.translate(table) for w in tokens]
        words = [word for word in stripped if word.isalpha()]
        stop_words = set(stopwords.words("english"))
        stop_words.discard("not")
        PS = PorterStemmer()
#         words = [w for w in words if not w in stop_words]
        words = [PS.stem(w) for w in words if not w in stop_words]
        words = ' '.join(words)
        all_reviews.append(words)
    return all_reviews

all_reviews = clean_text(data)
#all_reviews[0:20]

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/local/ZOHOCORP/abdul-pt6532/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [4]:

stopwords.words("english")

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [5]:
from sklearn.feature_extraction.text import CountVectorizer
CV = CountVectorizer(min_df=3)   
X = CV.fit_transform(all_reviews).toarray()
y = data.loc[:,["Review_class"]]
# print(np.shape(X))
# print(np.shape(y))
print(X)
print()
print(y)
print(type(X))
print(type(y))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

      Review_class
0              0.0
1              1.0
2              1.0
3              0.0
4              1.0
...            ...
1006           NaN
1007           NaN
1008           NaN
1009           NaN
1010           NaN

[2011 rows x 1 columns]
<class 'numpy.ndarray'>
<class 'pandas.core.frame.DataFrame'>


Representation of document1:  [[1 0 1 1 1 1 1 1 1 1 1 0]]
Representation of document2:  [[0 1 1 0 0 0 0 1 0 1 1 1]]


In [152]:
import torch
from torch.nn import MSELoss, Parameter

# The data function is: y = x + 10
x_train = torch.tensor(t1)
y_train = torch.tensor(t2, dtype=torch.float)

# Simple Linear Regression: a + bx
a = torch.randn(1, requires_grad=True, dtype=torch.float)
b = torch.randn(1, requires_grad=True, dtype=torch.float)
#print("h",a)
#print("h",b)
# If we use nn.Module to create a model, it will model.parameters()
model = [Parameter(a), Parameter(b)]
print(model)
criterion = MSELoss()
# optimizer = torch.optim.SGD(model, lr=0.1)
optimizer = torch.optim.Adam(model, lr=0.01)

for epoch in range(500):#500
    # Remove the grad computed in the last step
    optimizer.zero_grad()
    # Run a + bx
    y_predicted = model[0] + model[1] * x_train
     #print(x_train, y_train)
    print( y_train)
    print(y_predicted)
    loss = criterion(y_predicted, y_train)
    loss.backward()
    print()
    print("los is ",loss)
    print()
    optimizer.step()
    if epoch%500==0:
#print(model[0].grad)
       # print(model[1].grad)
 
    

[Parameter containing:
tensor([0.2269], requires_grad=True), Parameter containing:
tensor([0.0120], requires_grad=True)]
tensor([[0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 1., 1.]])
tensor([[0.2390, 0.2269, 0.2390, 0.2390, 0.2390, 0.2390, 0.2390, 0.2390, 0.2390,
         0.2390, 0.2390, 0.2269]], grad_fn=<AddBackward0>)

los is  tensor(0.3212, grad_fn=<MseLossBackward0>)

tensor([[0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 1., 1.]])
tensor([[0.2590, 0.2369, 0.2590, 0.2590, 0.2590, 0.2590, 0.2590, 0.2590, 0.2590,
         0.2590, 0.2590, 0.2369]], grad_fn=<AddBackward0>)

los is  tensor(0.3136, grad_fn=<MseLossBackward0>)

tensor([[0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 1., 1.]])
tensor([[0.2789, 0.2469, 0.2789, 0.2789, 0.2789, 0.2789, 0.2789, 0.2789, 0.2789,
         0.2789, 0.2789, 0.2469]], grad_fn=<AddBackward0>)

los is  tensor(0.3067, grad_fn=<MseLossBackward0>)

tensor([[0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 1., 1.]])
tensor([[0.2987, 0.2568, 0.2987, 0.2987, 0.2987, 0.2987, 0.2987,

tensor([[0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 1., 1.]])
tensor([[0.4034, 0.9568, 0.4034, 0.4034, 0.4034, 0.4034, 0.4034, 0.4034, 0.4034,
         0.4034, 0.4034, 0.9568]], grad_fn=<AddBackward0>)

los is  tensor(0.2003, grad_fn=<MseLossBackward0>)

tensor([[0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 1., 1.]])
tensor([[0.4033, 0.9579, 0.4033, 0.4033, 0.4033, 0.4033, 0.4033, 0.4033, 0.4033,
         0.4033, 0.4033, 0.9579]], grad_fn=<AddBackward0>)

los is  tensor(0.2003, grad_fn=<MseLossBackward0>)

tensor([[0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 1., 1.]])
tensor([[0.4032, 0.9589, 0.4032, 0.4032, 0.4032, 0.4032, 0.4032, 0.4032, 0.4032,
         0.4032, 0.4032, 0.9589]], grad_fn=<AddBackward0>)

los is  tensor(0.2003, grad_fn=<MseLossBackward0>)

tensor([[0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 1., 1.]])
tensor([[0.4032, 0.9599, 0.4032, 0.4032, 0.4032, 0.4032, 0.4032, 0.4032, 0.4032,
         0.4032, 0.4032, 0.9599]], grad_fn=<AddBackward0>)

los is  tensor(0.2003, grad_fn=<MseLossBackw

los is  tensor(0.2000, grad_fn=<MseLossBackward0>)

tensor([[0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 1., 1.]])
tensor([[0.4000, 1.0000, 0.4000, 0.4000, 0.4000, 0.4000, 0.4000, 0.4000, 0.4000,
         0.4000, 0.4000, 1.0000]], grad_fn=<AddBackward0>)

los is  tensor(0.2000, grad_fn=<MseLossBackward0>)

tensor([[0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 1., 1.]])
tensor([[0.4000, 1.0000, 0.4000, 0.4000, 0.4000, 0.4000, 0.4000, 0.4000, 0.4000,
         0.4000, 0.4000, 1.0000]], grad_fn=<AddBackward0>)

los is  tensor(0.2000, grad_fn=<MseLossBackward0>)

tensor([[0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 1., 1.]])
tensor([[0.4000, 1.0000, 0.4000, 0.4000, 0.4000, 0.4000, 0.4000, 0.4000, 0.4000,
         0.4000, 0.4000, 1.0000]], grad_fn=<AddBackward0>)

los is  tensor(0.2000, grad_fn=<MseLossBackward0>)

tensor([[0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 1., 1.]])
tensor([[0.4000, 1.0000, 0.4000, 0.4000, 0.4000, 0.4000, 0.4000, 0.4000, 0.4000,
         0.4000, 0.4000, 1.0000]], grad_fn=<AddBackw

## 

In [255]:

from sklearn.feature_extraction.text import CountVectorizer
document1 = 'Dog hates a cat It loves to go out and play'
document2 = 'Cat loves to play with a ball'

# converting sentences to lower case
document1 = document1.lower()
document2 = document2.lower()

# Intialize BoWs
count_vect = CountVectorizer()
# fit the corpus to CountVectorizer
count_vect.fit([document1, document2])

#--------print("feature names ", count_vect.get_feature_names())

# bag of word representation of document1
bow1 = count_vect.transform([document1])
t1=bow1.toarray()
print("Representation of document1: ", t1)

# bag of word representation of document2
bow2 = count_vect.transform([document2])
t2=bow2.toarray()
print("Representation of document2: ", t2)

# Output:
# feature names  ['and', 'ball', 'cat', 'dog', 'go', 'hates', 'it', 'loves', 'out', 'play', 'to', 'with']

# Representation of document1:  [[1 0 1 1 1 1 1 1 1 1 1 0]]
# Representation of document2:  [[0 1 1 0 0 0 0 1 0 1 1 1]]












import torch
import torch.nn as nn

# Linear regression
# f = w * x 

# here : f = 2 * x

# X = torch.tensor([[1], [2], [3], [4]], dtype=torch.float32)
# Y = torch.tensor([[2], [4], [6], [8]], dtype=torch.float32)
X = torch.tensor(t1, dtype=torch.float32)
Y = torch.tensor(t2, dtype=torch.float32)
# print(Y.shape)
# n_samples, n_features = X.shape
# print(f'#samples: {n_samples}, #features: {n_features}')
# 0) create a test sample
#X_test = torch.tensor([5], dtype=torch.float32)

# 1) Design Model, the model has to implement the forward pass!
# Here we can use a built-in model from PyTorch


# we can call this model with samples X
model = nn.Linear(1,12)


print(f'Prediction before training: = {model(X_test)}')

# 2) Define loss and optimizer
learning_rate = 0.01
n_iters = 151

loss = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# 3) Training loop
for epoch in range(n_iters):
    # predict = forward pass with our model
    y_predicted = model(X_test)

    # loss
    l = loss(Y, y_predicted)

    # calculate gradients = backward pass
    l.backward()

    # update weights
    optimizer.step()

    # zero the gradients after updating
    optimizer.zero_grad()
    
    if epoch % 10 == 0:
        print('loss = ', l)
print()
print("model parameterrs for best accuracy ------------------------")
for i,j in model.named_parameters():
    print(i,j)
print()
print("hyper parameters- for best accuracy --------------------------------")
print("learning rate",learning_rate,    "number of epochs:",epoch)
print(f"Prediction after training: {model(X_test)}")


Representation of document1:  [[1 0 1 1 1 1 1 1 1 1 1 0]]
Representation of document2:  [[0 1 1 0 0 0 0 1 0 1 1 1]]
Prediction before training: = tensor([ 5.8306, -0.4039, -3.4564, -4.4504, -1.6308, -5.2644, -5.6782,  2.5310,
         0.5546, -2.7881, -4.2664, -0.6186], grad_fn=<AddBackward0>)
loss =  tensor(15.4669, grad_fn=<MseLossBackward0>)
loss =  tensor(6.3770, grad_fn=<MseLossBackward0>)
loss =  tensor(2.6292, grad_fn=<MseLossBackward0>)
loss =  tensor(1.0840, grad_fn=<MseLossBackward0>)
loss =  tensor(0.4469, grad_fn=<MseLossBackward0>)
loss =  tensor(0.1843, grad_fn=<MseLossBackward0>)
loss =  tensor(0.0760, grad_fn=<MseLossBackward0>)
loss =  tensor(0.0313, grad_fn=<MseLossBackward0>)
loss =  tensor(0.0129, grad_fn=<MseLossBackward0>)
loss =  tensor(0.0053, grad_fn=<MseLossBackward0>)
loss =  tensor(0.0022, grad_fn=<MseLossBackward0>)
loss =  tensor(0.0009, grad_fn=<MseLossBackward0>)
loss =  tensor(0.0004, grad_fn=<MseLossBackward0>)
loss =  tensor(0.0002, grad_fn=<MseLossBa

# keeping learning rate to half and observing prediction .



In [248]:
learning_rate = 0.01/2
n_iters = 151

loss = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate) 

#3) Training loop
for epoch in range(n_iters):
    # predict = forward pass with our model
    y_predicted = model(X_test)

    # loss
    l = loss(Y, y_predicted)

    # calculate gradients = backward pass
    l.backward()

    # update weights
    optimizer.step()

    # zero the gradients after updating
    optimizer.zero_grad()
    
    if epoch % 10 == 0:
        print(' loss = ', l)
print()
print("model parameterrs for best accuracy ------------------------")
for i,j in model.named_parameters():
    print(i,j)
print()
print("hyper parameters- for best accuracy --------------------------------")
print("learning rate",learning_rate,    "number of epochs:",epoch)
print(f"Prediction after training: {model(X_test)}")

    
    
    

 loss =  tensor(1.8271e-11, grad_fn=<MseLossBackward0>)
 loss =  tensor(1.2446e-11, grad_fn=<MseLossBackward0>)
 loss =  tensor(8.7581e-12, grad_fn=<MseLossBackward0>)
 loss =  tensor(6.4183e-12, grad_fn=<MseLossBackward0>)
 loss =  tensor(4.8671e-12, grad_fn=<MseLossBackward0>)
 loss =  tensor(3.9351e-12, grad_fn=<MseLossBackward0>)
 loss =  tensor(3.2100e-12, grad_fn=<MseLossBackward0>)
 loss =  tensor(2.8242e-12, grad_fn=<MseLossBackward0>)
 loss =  tensor(2.5887e-12, grad_fn=<MseLossBackward0>)
 loss =  tensor(2.4845e-12, grad_fn=<MseLossBackward0>)
 loss =  tensor(2.4677e-12, grad_fn=<MseLossBackward0>)
 loss =  tensor(2.4677e-12, grad_fn=<MseLossBackward0>)
 loss =  tensor(2.4677e-12, grad_fn=<MseLossBackward0>)
 loss =  tensor(2.4514e-12, grad_fn=<MseLossBackward0>)
 loss =  tensor(2.4514e-12, grad_fn=<MseLossBackward0>)
 loss =  tensor(2.4514e-12, grad_fn=<MseLossBackward0>)

model parameterrs for best accuracy ------------------------
weight Parameter containing:
tensor([[-0.0